version: "1"

services:
  comfyui:
    build: .

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    ports:
      - 7860:7860
    
    volumes:
      - /var/cache/file_cache/comfyui:/data/models
      - comfyui_output:/data/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  comfyui_output:
